name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine3.15
    steps:
      - name: log node version
        run: |
          node node-v
          cat /etc/os-release