name: DOD check

on:
  workflow_dispatch:
   
jobs:
  DODtest:
    runs-on: ubuntu-latest

    steps:
     - name: chechkout code
       uses: actions/checkout@v3
       with:
         ref: DOD_check
         fetch-depth: 0   

     - name: install npm, js-yaml, yq
       id: installation
       run: |
         npm install js-yaml -y
         npm install yq -y
         npm install jq -y
         yq --version
         jq --version
         pwd
         ls -la
         js-yaml values.yaml > values.json
         jq 'LOG_LEVEL' values.json

         