name: DOD check

on:
  workflow_dispatch:
   
jobs:
  DODtest:
    runs-on: ubuntu-latest

    steps:
     - name: chechkout code
       uses: actions/checkout@v3
       with:
         ref: DOD_check
         fetch-depth: 0   

     - name: install npm, js-yaml, yq
       id: installation
       run: |
         npm install js-yaml -y
         npm install yq -y
         yq --version
         log_level_value=$(yq '.env[] | select(.name == "LOG_LEVEL") | .value ' values.yaml)
         echo $log_level_value
       env:
         a: ${{ steps.installation.outputs.message }}

     - name: store the output of installation step here
       id: storing
       run: |
         log=$a
         echo $log

         


        

         