name: DOD check

on:
  workflow_dispatch:
   
jobs:
  DODtest:
    runs-on: ubuntu-latest

    steps:
     - name: chechkout code
       uses: actions/checkout@v3
       with:
         ref: master
         fetch-depth: 0   

     - name: install npm, js-yaml, yq
       id: installation
       run: |
         npm install js-yaml -y
         