name: Environment Variable

on: push

env:
  WF_ENV: Available to all jobs

jobs:
  log-env:
    runs-on: ubuntu-latest
    env: 
      JOB_ENV: Available to all the steps in log-env job
    steps:
      - name: Log ENV Variable
        env: 
          STEP_ENV: Available to only this particular step
        run: |
          echo "wf_env: ${WF_ENV}"
          echo "job-env: ${JOB_ENV}"
          echo "step_env: ${STEP_ENV}"
      - name: Log ENV Variable 2
        run: |
          echo "wf_env: ${WF_ENV}"
          echo "job-env: ${JOB_ENV}"
          echo "step_env: ${STEP_ENV}"
  
  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: Default ENV Variable
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "wf_env: ${WF_ENV}"
          echo "job-env: ${JOB_ENV}"
          echo "step_env: ${STEP_ENV}"