name: Lint code base

on:
  push:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
     - name: chechkout code
       uses: actions/checkout@v3
       with:
         fetch-depth: 0

     - name: Lint Code Base
       uses: github/super-linter@v4
       env:
         VALIDATE_ALL_CODEBASE: false
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}